# Generated by Django 2.0.1 on 2018-01-08 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='mail',
            new_name='email',
        ),
    ]
